[project]
name = "nnx-mlflow-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flax>=0.10.4",
    "grain>=0.2.3",
    "jax[cuda12]>=0.5.3",
    "keras>=3.9.0",
    "mlflow>=2.21.0",
    "optax>=0.2.4",
]
